package com.tch.youmuwa.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tch.youmuwa.dao.EmployerSearchHistory;
import com.tch.youmuwa.dao.UserInfo;
import com.tch.youmuwa.dao.WorkerSearchHistory;

import com.tch.youmuwa.dao.EmployerSearchHistoryDao;
import com.tch.youmuwa.dao.UserInfoDao;
import com.tch.youmuwa.dao.WorkerSearchHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig employerSearchHistoryDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig workerSearchHistoryDaoConfig;

    private final EmployerSearchHistoryDao employerSearchHistoryDao;
    private final UserInfoDao userInfoDao;
    private final WorkerSearchHistoryDao workerSearchHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        employerSearchHistoryDaoConfig = daoConfigMap.get(EmployerSearchHistoryDao.class).clone();
        employerSearchHistoryDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        workerSearchHistoryDaoConfig = daoConfigMap.get(WorkerSearchHistoryDao.class).clone();
        workerSearchHistoryDaoConfig.initIdentityScope(type);

        employerSearchHistoryDao = new EmployerSearchHistoryDao(employerSearchHistoryDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        workerSearchHistoryDao = new WorkerSearchHistoryDao(workerSearchHistoryDaoConfig, this);

        registerDao(EmployerSearchHistory.class, employerSearchHistoryDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(WorkerSearchHistory.class, workerSearchHistoryDao);
    }
    
    public void clear() {
        employerSearchHistoryDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        workerSearchHistoryDaoConfig.clearIdentityScope();
    }

    public EmployerSearchHistoryDao getEmployerSearchHistoryDao() {
        return employerSearchHistoryDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public WorkerSearchHistoryDao getWorkerSearchHistoryDao() {
        return workerSearchHistoryDao;
    }

}
