package com.tch.zx.dao.green;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TAB_BAR".
*/
public class TabBarDao extends AbstractDao<TabBar, Long> {

    public static final String TABLENAME = "TAB_BAR";

    /**
     * Properties of entity TabBar.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TypeId = new Property(1, int.class, "typeId", false, "TYPE_ID");
        public final static Property TypeStr = new Property(2, String.class, "TypeStr", false, "TYPE_STR");
    }


    public TabBarDao(DaoConfig config) {
        super(config);
    }
    
    public TabBarDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TAB_BAR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 1: typeId
                "\"TYPE_STR\" TEXT);"); // 2: TypeStr
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TAB_BAR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TabBar entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTypeId());
 
        String TypeStr = entity.getTypeStr();
        if (TypeStr != null) {
            stmt.bindString(3, TypeStr);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TabBar entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTypeId());
 
        String TypeStr = entity.getTypeStr();
        if (TypeStr != null) {
            stmt.bindString(3, TypeStr);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TabBar readEntity(Cursor cursor, int offset) {
        TabBar entity = new TabBar( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // typeId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // TypeStr
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TabBar entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTypeId(cursor.getInt(offset + 1));
        entity.setTypeStr(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TabBar entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TabBar entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TabBar entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
